import React, { FC } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navigation/Navbar";
import { Box } from "@mui/material";
import {Container, styled} from "@mui/system";

interface Props {
  children: JSX.Element | JSX.Element[];
}


const Wrapper = styled(Container)`
  width: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;

`




const Layout: FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Wrapper>{children}</Wrapper>
      </main>
    </>
  );
};

export default Layout;
